# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preds', '0002_question_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerable_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 12, 12, 0)),
            preserve_default=False,
        ),
    ]
