# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preds', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
